// Generated by Wrangler by running `wrangler types`

interface Env {
	GEO_KV: KVNamespace;
	CHAT_ROOM: DurableObjectNamespace<import("./src/index").ChatRoom>;
	MATCH_LOBBY: DurableObjectNamespace<import("./src/index").MatchLobby>;
	MEDIA_BUCKET: R2Bucket;
	DB: D1Database;
	LV_AI: AnalyticsEngineDataset;
	AI: Ai;
}
